# Generated by Django 3.1 on 2020-12-13 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APPLICATION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'APPLICATION',
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vendors', models.CharField(max_length=32)),
                ('system', models.CharField(max_length=32)),
                ('region', models.CharField(max_length=32)),
                ('ip', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('configuration', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'IDC',
            },
        ),
        migrations.CreateModel(
            name='LANUAGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lanuage', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'LANUAGE',
            },
        ),
        migrations.CreateModel(
            name='ENV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.CharField(max_length=32)),
                ('lanuage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_app.lanuage')),
            ],
            options={
                'db_table': 'ENV',
            },
        ),
        migrations.CreateModel(
            name='DOMAIN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=128)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_app.application')),
            ],
            options={
                'db_table': 'DOMAIN',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='env',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_app.env'),
        ),
        migrations.AddField(
            model_name='application',
            name='idc',
            field=models.ManyToManyField(related_name='APPLICATION', to='property_app.IDC'),
        ),
    ]
